#!/command/with-contenv bash

source /assets/functions/00-container
PROCESS_NAME="matomo"

check_service_initialized init 20-php-fpm

sanity_db
db_ready mariadb

if [ ! -f "${NGINX_WEBROOT}"/index.php ]; then
        print_warn "No Matomo Installation Found, Installing..."
        mkdir -p "${NGINX_WEBROOT}"
        curl https://builds.matomo.org/piwik-latest.tar.gz | tar xfz - --strip 1 -C "${NGINX_WEBROOT}"
        curl https://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz | gunzip -c > "${NGINX_WEBROOT}"/misc/GeoIPCity.dat
        print_info "Install Complete"
fi

echo "*/${CRON_PERIOD} * * * * sudo -u ${NGINX_USER} TZ=${TIMEZONE} php ${NGINX_WEBROOT}/console core:archive >/dev/null 2>&1" > /assets/cron/matomo_archive_reports
echo "alias console='cd ${NGINX_WEBROOT}; sudo -u ${NGINX_USER} php ./console'" >> /root/.bashrc
chown -R "${NGINX_USER}":"${NGINX_GROUP}" "${NGINX_WEBROOT}"

liftoff
