#!/command/with-contenv bash

source /assets/functions/00-container
PROCESS_NAME="matomo"

check_service_initialized init 10-unit

sanity_db
db_ready mariadb

if [ ! -f "${UNIT_WEBROOT}"/index.php ]; then
        print_warn "No Matomo Installation Found, Installing..."
        mkdir -p "${UNIT_WEBROOT}"
        curl https://builds.matomo.org/piwik-latest.tar.gz | tar xfz - --strip 1 -C "${UNIT_WEBROOT}"
        curl https://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz | gunzip -c > "${UNIT_WEBROOT}"/misc/GeoIPCity.dat
        print_info "Install Complete"
fi

echo "*/${CRON_PERIOD} * * * * sudo -u ${UNIT_USER} TZ=${TIMEZONE} php ${UNIT_WEBROOT}/console core:archive >/dev/null 2>&1" > /assets/cron/matomo_archive_reports
echo "alias console='cd ${UNIT_WEBROOT}; sudo -u ${UNIT_USER} php ./console'" >> /root/.bashrc
chown -R "${UNIT_USER}":"${UNIT_GROUP}" "${UNIT_WEBROOT}"

liftoff
