#!/usr/bin/with-contenv bash

if [ ! -f /tmp/state/10-nginx ]; then

while [ ! -f /tmp/state/99-container-init ]
do
  sleep 1
done
  
  ### Adjust Runtime Variables
  sed -i -e "s/<CRON_PERIOD>/$CRON_PERIOD/g" /assets/cron/crontab.txt

  ### Make sure that DB is accessible
  while true; do
    mysqlcmd='mysql -u'$DB_USER' -h'$DB_HOST' -p'$DB_PASS 
    out="`$mysqlcmd -e "SELECT COUNT(*) FROM information_schema.FILES;" 2>&1`"
    echo "$out" | grep -E "COUNT|Enter" 2>&1 > /dev/null
    if [ $? -eq 0 ]; then
      echo "MySQL Server is up !"
      break
    fi
    echo "DB server still isn't up, sleeping a little bit ..."
    sleep 2
  done

  echo 'geoip.custom_directory=/www/piwik/misc' >> /etc/php7/php.ini
  echo 'geoip.custom_directory=/www/piwik/misc' >> /etc/php7/conf.d/00_geoip.ini
   


  ### Check to see if Piwik Installed, if not, download and setup..
  if [ ! -f /www/piwik/piwik.php ]; then
          echo '### No Piwik Installation Found, Installing...'
          mkdir -p /www/piwik
          curl https://builds.piwik.org/piwik-latest.tar.gz | tar xvfz - --strip 1 -C /www/piwik
          curl https://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz | gunzip -c >/www/piwik/misc/GeoIPCity.dat
          curl https://raw.githubusercontent.com/cerlestes/piwik/cerlestes-patch-1/libs/MaxMindGeoIP/geoip.inc > /www/piwik/libs/MaxMindGeoIP/geoip.inc
          chmod +x /www/piwik/libs/MaxMindGeoIP/geoip.inc
  fi

  ### Set Permissions
  chown -R nginx:www-data /www/piwik

    ## Start nginx
    mkdir -p /www/logs/nginx
    mkdir -p /tmp/nginx
    chown -R nginx /www/logs/nginx
    chown nginx /tmp/nginx
    mkdir -p /tmp/state
    echo 'Initialization Complete' >/tmp/state/10-nginx
fi

echo ''
echo '** Starting nginx..'
exec nginx
