#!/usr/bin/with-contenv bash

if [ ! -f /tmp/state/10-nginx ]; then
  
  ### Adjust Runtime Variables
  sed -i -e "s/<CRON_PERIOD>/$CRON_PERIOD/g" /assets/cron/crontab.txt

  ### Make sure that DB is accessible
  while true; do
    mysqlcmd='mysql -u'$DB_USER' -h'$DB_HOST' -p'$DB_PASS 
    out="`$mysqlcmd -e "SELECT COUNT(*) FROM information_schema.FILES;" 2>&1`"
    echo "$out" | grep -E "COUNT|Enter" 2>&1 > /dev/null
    if [ $? -eq 0 ]; then
      echo "** [matomo] MySQL Server "$DB_HOST" is up !"
      break
    fi
    echo "** [matomo] MySQL Server "$DB_HOST" still isn't up, sleeping a little bit ..."
    sleep 2
  done

  echo 'geoip.custom_directory=/www/matomo/misc' >> /etc/php7/php.ini
  echo 'geoip.custom_directory=/www/matomo/misc' >> /etc/php7/conf.d/00_geoip.ini
   


  ### Check to see if Matomo Installed, if not, download and setup..
  if [ ! -f /www/matomo/index.php ]; then
          echo '** [matomo] # No Piwik Installation Found, Installing...'
          mkdir -p /www/matomo
          curl https://builds.matomo.org/matomo-latest.tar.gz | tar xvfz - --strip 1 -C /www/matomo
          curl https://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz | gunzip -c >/www/matomo/misc/GeoIPCity.dat
          curl https://raw.githubusercontent.com/cerlestes/matomo/cerlestes-patch-1/libs/MaxMindGeoIP/geoip.inc > /www/matomo/libs/MaxMindGeoIP/geoip.inc
          chmod +x /www/matomo/libs/MaxMindGeoIP/geoip.inc
  fi

  ### Set Permissions
    chown -R nginx:www-data /www/matomo

    mkdir -p /tmp/state
    echo 'Initialization Complete' >/tmp/state/10-nginx
fi

echo ''
echo '** [matomo] Starting nginx'
exec nginx
