#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/10-matomo-init ]
do
  sleep 1
done

if [ ! -f /tmp/state/10-nginx ]; then
    mkdir -p /tmp/state
    echo 'Initialization Complete' >/tmp/state/10-nginx
fi

echo ''
echo '** [matomo] Starting nginx'
exec nginx
